First of all read about the assignment problem; https://en.wikipedia.org/wiki/Assignment_problem we are modelling players as agents and jobs

Here is the example from [https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linear_sum_assignment.html] but this one is confusing for two reasons

* the assignments are not symmetric
* it is possible for a player to play himself. 

But it finds us the minimum cost assignment using the hungarian algorithm and even tells us the sum of the cost, which is 5

In [8]:
import numpy as np

cost = np.array([[4, 1, 3], 
                 [2, 0, 5], 
                 [3, 2, 2]])


from scipy.optimize import linear_sum_assignment

row_ind, col_ind = linear_sum_assignment(cost)

print( col_ind )
print( row_ind )

cost[row_ind, col_ind].sum()

[1 0 2]
[0 1 2]


5

Let's do the same thing again but using something more akin to gaming 


![alt textdsadsa](https://lh3.googleusercontent.com/xFo-YSvknFO2fwEH_RQ9Bs_enHuQaMIqjxfJok6ZgpGbFqWGjsViYo4I1o7KBr6SpkoYStL_0Wd0fkQmhNiQPugSZofRizpHVmY8ccRpOPG4LjBEmsB3xXefSsisNY4CSczU8gDDiU3AKoc6L7En92TtHet0pS7ymW5xm_cds3aVjob7AFGCMhTuaVS8H60TlTnonOiTo-N6sPv5Di7tji9hYMQg4_2P_t-k_Ql2HIsnlm4Cus3tZDt4Vn65o69QXX31RGI6a0c_6UXofyy2n32K3g6NKyok4JF1g11tBFnYXDqURuKXqQ01R0IFms8fXHkNRVCUXvTNw0P8BDc0QnwPfQCfjuSrxKCKA_yru6FRmr-wU1udnY_TPeEh0MO4cOqsW1UzzRVK1KzVFv1hghPXGvg5spXMTOTxyFh9sUGUcu5hUbfjRIoQivzZEglE0h-qzp63g7dyW7s2OD4Boe-nh-zYj7vKk5ZrGg4699UMNwm-27XPzsM95UNJb7ndgGfpONiSrgiBwZwfq6pwffZseYQkzvzrNVebooIzgDjZ5cW2Rkxj8UYvTyJRe1-j6bfk-JYN6E4x8K1ttouJiDCE_Jx1admJNDHB1j0g0ZCVMMLyH3kPZisPpgYgdwxHUMpC0nrS3ajNCqPvb0oBVwgxSmg=w1027-h991-no "Logo Title Text dsadsa")

In [4]:
import numpy as np
import math

cost = np.array([[math.inf, 5, 10], 
                 [5, math.inf, 3], 
                 [10, 3, math.inf]])


from scipy.optimize import linear_sum_assignment

row_ind, col_ind = linear_sum_assignment(cost)

print( col_ind )
print( row_ind )

cost[row_ind, col_ind].sum()

[1 2 0]
[0 1 2]


18.0


![alt textdsssadsa](https://lh3.googleusercontent.com/wE6d506GBNZu4_0jcfZiTsnENsOgU8UxhiToObd45Syru6X69hZNT0aL-QoykUsLrMPX593I1McWIo5NMldVZXOLtMUqLmRteAxOaRelU8CagOVW93Aj7drHeUjraPDmNC3bR9xIzJCXtcqh6EGeLwsRRFEdoyD_pjo5B64T3KU9KKeCZfo72PXLu-XvuKDsCA7yoRRatqMaInFOj0Dskcmj2VBOvHDYD3bytAmx3IGdvSn4-JlMk486y1ebZBq4uHDhGSKiZryo8gVV_-1sTtI84cWmodFPZFyApz_G0WchkMWL0B-CzqPSh2E7kxzQrdlPe5E-ZNuKy04kGgFX4koxzL6gjId5QRf0pG0pwulwvWZo1_pMfzQdVbhQB8BaTn1EnE-fjdnmR2-EaRF6nAqnFZdHp-PC92bGHViCYjkF82sGdE0MLPSvKwWgTWNjHazgZ3y9wff6b0-Mx1THLh8VJypodc8VLAwnOLcIBQ6sTGT0orO-pmP-LGVya2LscPaVvS8lBliFidKMuG7Ne2T-TmmeDf44z39iCNY4Tj23j7Xgt3NJkz0EStScgY5efAWIKSXOHq0QoN14RTb9LmIth8YWBQ9IvG8wY2zYD_oNg1GVPecDDqTIsNHR8ZSKLyvEUaWmi9VZjIIoIZHLYZWwfIY=w991-h758-no "Logo Title Text ssdsadsa")




OK, getting there, but notice that it's doing something very weird player 3 is getting 2 games (hes playing p1 and p2). This is weird because the assignment problem should assign only 1 thing i.e. "It is required to perform all tasks by assigning exactly one agent to each task and exactly one task to each agent in such a way that the total cost of the assignment is minimized." I can only assume this is because of the hungarian algorithm, and if the assignment LP was calculated directly it would fail for a matrix with an odd number i.e. 3x3

So let's try with a 4x4


In [5]:
import numpy as np
import math

cost = np.array([[math.inf, 5, 10, 3], 
                 [5, math.inf, 3, 1], 
                 [10, 3, math.inf, 5],
                  [3, 1,  5, math.inf]])


from scipy.optimize import linear_sum_assignment

row_ind, col_ind = linear_sum_assignment(cost)

print( col_ind )
print( row_ind )

cost[row_ind, col_ind].sum()

[3 2 1 0]
[0 1 2 3]


12.0



![alt text](https://lh3.googleusercontent.com/lti7GIAmznGf9H8G7yaI8_C99harkDbfzma_UzWDxPGE2M26pa0yKW9T2nYpgQubMnE1KKhMnT-_9ufLGnAW8TGMOrup7qX8vxBLAU_4zdYHwnKRmQGzQrJDZmXJiEtSFh1ebu3okB7V9jz8ZaNvfNo3maJSBSDiNMgl0SoefjhRgEirHSj8jx9Mb01_mfROKDYTQWnueNSVHEsPpLsvJvyqbEJzv9vlLAwchz8T3wYtxMfU4OZk2u4F7_ZGX4en1DxUlRGqwmxNa5O9Hc4hCVa4TSBWN2bCWOSu2N1UHKVzwGfYJhhfSkgH9h_FMEsIjm93LptKuvAdXpdyh7Y-yZKiM6ujwV5mAPCi4MCEHmWJcWuZNxnssF34pwTGVWV2g6pijgDeKra1-aQZPgChch3J5VLIAV2gnnKi6aozGD1KVpe-0fWF8Mo5-DmCQIT5MmrZnbZFIWBFMwLUkrtCTDbv92z3_SPHUXdeAp1Y4ExisOJMLYF32jtOCxLWy6vaokeTNZHR4u1jOPfjkz9zyqGGXnpZhhnEcTxFu-2FU1Ck8Kfi0y_qa-KlMRrtYjv2XBflYHSrugMJYvc78mp6EnfTyf0V34cNhA=w777-h686-no "Logo Title Text 1")

So this algorithm is saying that;

* Person 1 should play person 4
* Person 4 should play person 1 (note the symmetry)

and.. 

* Person 2 should play person 3  
* Person 3 should play person 2 (note the symmetry)